server:
  port: 8080

spring:
  config:
    import: "optional:file:.env"  # .env читається без [.properties]

  data:
    redis:
      host: {REDIS_HOST}
      port: {REDIS_PORT}

  application:
    name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-ttl: 900000000  # 15 хв = 15*60*1000=90000
  refresh-token-ttl: 604800000  # 7 днів = 7*24*60*60*1000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}