server:
  port: 8084

security:
  excluded-urls:
    - /auth/**

spring:
  application:
    name: user-service
#
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  config:
    import: optional:file:.env[.properties]
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: postgresql
#
#  mongodb:
#    url: ${MONGODB_URI}
#    database: ${MONGODB_DATABASE}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}