server:
  port: 8083

spring:

  application:
    name: chat-service

  rabbitmq:
    host: {RABBIT_HOST}
    port: {RABBIT_PORT}
    username: {RABBIT_USERNAME}
    password: {RABBIT_PASSWORD}

  data:
    mongodb:
      uri: {MONGO_URI}
#      username: dfdfd
#      password: ew
#docker exec -it my-mongo mongo -u admin -p secret --authenticationDatabase admin